export { CatalogPage } from './catalog-page';
export {
  sampleCta,
  sampleFaq,
  sampleImageBreak,
  sampleImageGallery,
  sampleInfoGrid,
  sampleInfoTable,
  sampleLead,
  sampleLogoCloud,
  sampleMapWithInfo,
  sampleMediaBlock,
  sampleNewsList,
  sampleRichText,
  sampleStatsCounter,
  sampleStepListDated,
  sampleStepListNumbered,
  sampleTestimonial,
  sampleTextCardGrid,
  sampleTextCardGridWithImage,
  sampleVisualSlideshow,
} from './data';
